version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wb-tariffs-app
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5450
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=wb_tariffs
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/credentials.json
      - GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID}
      - UPDATE_INTERVAL=3600000
    volumes:
      - ./credentials:/app/credentials
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: wb-tariffs-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wb_tariffs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5450:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: 