version: '3.8'

services:
  postgres:
    image: postgres:14.8-alpine3.18
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5450:5432"
volumes:
  postgres_data: 