version: '3.8'

services:
  postgres:
    image: postgres:14.8-alpine3.18
    env_file:
      - ../.env
    environment:
      - POSTGRES_DB=wb_tariffs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
volumes:
  postgres_data: 